
-- Create about_content table
CREATE TABLE about_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section VARCHAR(50) NOT NULL UNIQUE, -- e.g., 'intro', 'contact'
  content TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_by UUID REFERENCES auth.users(id) -- Optional: track who updated
);

-- Enable Row Level Security
ALTER TABLE about_content ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Enable read access for all users" ON about_content
  FOR SELECT USING (true);

-- Create policy for admin update access (assuming admin users have a specific role or metadata, 
-- but for simplicity here we might check if user is authenticated. 
-- In a real app, you'd check for specific admin claims or a separate admins table.)
-- For now, let's assume any authenticated user can update (since we only have admin login).
CREATE POLICY "Enable update access for authenticated users" ON about_content
  FOR UPDATE USING (auth.role() = 'authenticated');

-- Create policy for admin insert access (initial population)
CREATE POLICY "Enable insert access for authenticated users" ON about_content
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Create audit log table for about_content
CREATE TABLE about_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  about_content_id BIGINT REFERENCES about_content(id),
  old_content TEXT,
  new_content TEXT,
  changed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  changed_by UUID REFERENCES auth.users(id)
);

-- Function to handle audit logging
CREATE OR REPLACE FUNCTION log_about_changes()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO about_audit_log (about_content_id, old_content, new_content, changed_by)
  VALUES (OLD.id, OLD.content, NEW.content, auth.uid());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for audit logging
CREATE TRIGGER on_about_change
  AFTER UPDATE ON about_content
  FOR EACH ROW
  EXECUTE PROCEDURE log_about_changes();

-- Insert initial data
INSERT INTO about_content (section, content) VALUES
('intro', '<p style="margin-bottom: 20px;">Tedoori is an architectural practice based in Seoul.</p><p>We focus on the essential qualities of space and structure, exploring the relationship between form and function.</p>'),
('contact', '<p>Email: info@tedoori.com</p><p>Tel: +82 2 1234 5678</p><p>Address: 123, Sejong-daero, Jongno-gu, Seoul, Republic of Korea</p>');
